# Generated by Django 5.2.7 on 2025-10-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="default_profile_pic.jpg",
                null=True,
                upload_to="profile_pictures",
            ),
        ),
    ]
